### ISSUE TITLE
[Fixed] Crash on server (Exception in server tick loop)

### ISSUE THREAD

**Issue by AzzyDR** [Toshayo/WaterFrames#1]
Spacehobo sent me to tell you that the mod works in singleplayer but if put into a server it seems to be calling onto the server for watermedia which cant happen because watermedia is a display library you need to set exceptions for servers

heres the crash report

Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: org.apache.logging.log4j.Logger.fatal(Lorg/apache/logging/log4j/Marker;Ljava/lang/String;Ljava/lang/Object;)V
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoSuchMethodError: org.apache.logging.log4j.Logger.fatal(Lorg/apache/logging/log4j/Marker;Ljava/lang/String;Ljava/lang/Object;)V
	at org.watermedia.core.exceptions.IllegalEnvironmentException.<init>(IllegalEnvironmentException.java:12)
	at net.toshayo.waterframes.WaterMediaLoader.<init>(WaterMediaLoader.java:50)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at cpw.mods.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:173)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:506)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 5 more

**Comment by AzzyDR** [comment]
this line is where it's asking for watermedia library i have it there but watermedia library doesn't work in servers

at org.watermedia.core.exceptions.IllegalEnvironmentException.<init>(IllegalEnvironmentException.java:12)
	at net.toshayo.waterframes.WaterMediaLoader.<init>(WaterMediaLoader.java:50)

**Comment by AzzyDR** [comment]
[Server thread/ERROR] [waterframes]: Skipping event FMLModIdMappingEvent and marking errored mod waterframes since required dependency watermedia has errored

there is also this in the log as it crashes might have something to do with it

**Comment by AzzyDR** [comment]
ok it is foamfix adding the log4j fix to watermedia

**Comment by AzzyDR** [comment]
you may have to make a lineof code to disable watermedia from loading when its in a server for 1.7.10

you may be able to do check to see if a server client is running and then activate code to disable forge from loading water media and just pulling assets for the mod from the mod
